const ROUTES = Object.freeze({
  WELCOME: "/DEAI_Project/",
  DOCS: "/DEAI_Project/docs",
  ABOUT: "/DEAI_Project/about",
  CONTACT: "/DEAI_Project/contact",
  SERVICES: "/DEAI_Project/Services",
  APIs: "/DEAI_Project/apis",
  FQA: "/DEAI_Project/fqa",
  LOGIN: "/DEAI_Project/login",
  REGISTER: "/DEAI_Project/register",
  PROFILE: "/DEAI_Project/profile",
  NOT_FOUND: "*",
  SERVER_ERROR: "/DEAI_Project/500",
  FORBIDDEN: "/DEAI_Project/403",
  UNAUTHORIZED: "/DEAI_Project/401",
  RESET_PASSWORD: "/DEAI_Project/reset-password",
  RESET_PASSWORD_CONFIRM: "/DEAI_Project/reset-password-confirm",
  FORGET_PASSWORD: "/DEAI_Project/change-password",
  CHANGE_PASSWORD_CONFIRM: "/DEAI_Project/change-password-confirm",
  VERIFY_EMAIL: "/DEAI_Project/verify-email",
  VERIFY_EMAIL_CONFIRM: "/DEAI_Project/verify-email-confirm",
  VERIFY_PHONE: "/DEAI_Project/verify-phone",
  VERIFY_PHONE_CONFIRM: "/DEAI_Project/verify-phone-confirm",
  DASHBOARD: "/DEAI_Project/dashboard",
  DASHBOARD_CHAT: "/DEAI_Project/dashboard/chat",
  DASHBOARD_STATICS: "/DEAI_Project/dashboard/statics",
  DASHBOARD_APPOINTMENTS: "/DEAI_Project/dashboard/appointments",
  DASHBOARD_PERFORMANCE: "/DEAI_Project/dashboard/performance",
  DASHBOARD_TASKS: "/DEAI_Project/dashboard/tasks",
  DASHBOARD_PLATFORMS: "/DEAI_Project/dashboard/platforms",
});

export default ROUTES;
