const ROUTES = Object.freeze({
  WELCOME: "/DEAI-Project/",
  DOCS: "/DEAI-Project/docs",
  ABOUT: "/DEAI-Project/about",
  CONTACT: "/DEAI-Project/contact",
  SERVICES: "/DEAI-Project/Services",
  APIs: "/DEAI-Project/apis",
  FQA: "/DEAI-Project/fqa",
  LOGIN: "/DEAI-Project/login",
  REGISTER: "/DEAI-Project/register",
  PROFILE: "/DEAI-Project/profile",
  NOT_FOUND: "*",
  SERVER_ERROR: "/DEAI-Project/500",
  FORBIDDEN: "/DEAI-Project/403",
  UNAUTHORIZED: "/DEAI-Project/401",
  RESET_PASSWORD: "/DEAI-Project/reset-password",
  RESET_PASSWORD_CONFIRM: "/DEAI-Project/reset-password-confirm",
  FORGET_PASSWORD: "/DEAI-Project/change-password",
  CHANGE_PASSWORD_CONFIRM: "/DEAI-Project/change-password-confirm",
  VERIFY_EMAIL: "/DEAI-Project/verify-email",
  VERIFY_EMAIL_CONFIRM: "/DEAI-Project/verify-email-confirm",
  VERIFY_PHONE: "/DEAI-Project/verify-phone",
  VERIFY_PHONE_CONFIRM: "/DEAI-Project/verify-phone-confirm",
  DASHBOARD: "/DEAI-Project/dashboard",
  DASHBOARD_CHAT: "/DEAI-Project/dashboard/chat",
  DASHBOARD_STATICS: "/DEAI-Project/dashboard/statics",
  DASHBOARD_APPOINTMENTS: "/DEAI-Project/dashboard/appointments",
  DASHBOARD_PERFORMANCE: "/DEAI-Project/dashboard/performance",
  DASHBOARD_TASKS: "/DEAI-Project/dashboard/tasks",
  DASHBOARD_PLATFORMS: "/DEAI-Project/dashboard/platforms",
});

export default ROUTES;
